### ISSUE TITLE
Remove exportTrailingSlash flag from the next.config.js

### ISSUE THREAD

**Issue by viktor-yakubiv** [oacore/about#225]
Comes from #223 but needs to be done separately since requires additional testing and server configuration.

@mcancellieri, @samuelpearce it would be nice to do it so to get consistent URLs if this is possible.

**Comment by Joozty** [comment]
@viktor-yakubiv What's the desired behaviour path with trailing slashes should be redirected to path without trailing slash, i.e. core.ac.uk/data/ -> core.ac.uk/data


Next.js 9.5 introduced an [option](https://nextjs.org/blog/next-9-5#optional-trailing-slash-in-urls) for it. Maybe it can help?
