### ISSUE TITLE
Select a content management system

### ISSUE THREAD

**Issue by viktor-yakubiv** [oacore/about#364]
In the [Next.js docs about preview mode](https://nextjs.org/docs/advanced-features/preview-mode#securely-accessing-it-from-your-headless-cms) is a list of headless CMSs we could possibly use for our website. The goal is to go through the list and select the one that suits us the most.

### Selection criteria

- **Price:** we target free ones, but it's important to know how much and for what exactly we pay (per user, per website)
    - **Open-source supporter:** good to know if there are payed features free for open science/open source
- **Preview mode:** the CMS must have a way to operate with preview pages; this is a feature allowing open different page on the website that picks the edits up automatically
- **Internationalisation:** it would be nice to have many languages supported for free; where it's not possible, how much it costs
- **User roles:** 3 roles is enough for us, but if we want to let external people edit the website (like let Ambassadors edit their info themselves) we need more; if the monetising model is based on users themselves, it's not good but 5-6 should fit our team
- **Resource management:** how does the CMS process pictures, where it stores them, what kinds of pictures are supported (SVG is important to have); it's not a problem if no info is available here
- **Structure of data:** is it possible to setup more than one website in a single CMS instance/account
- **Self-hosted:** it's not that important, easier to maintain if hosted externally, safer if hosted ourselves
- **Subjective impression:** does it look easy to setup the content, navigate through the content
- **API:** only link to the docs needed, @viktor-yakubiv will go through it manually
- **Rich text outputting format:** how does rich text looks in the API output; could be also tested by a developer

### The list of CMSs

- DatoCMS
- TakeShape
- Sanity
- Prismic
- Contentful
- Strapi
- Agility CMS
- Cosmic
- ButterCMS
- Storyblok
- GraphCMS
- Kontent

**Comment by hanana1** [comment]
The file with results https://docs.google.com/spreadsheets/d/1_UwTkwJR2JNM848nVodfHkGdyIzK6njq08uAWX6i_rA/edit#gid=0

**Comment by viktor-yakubiv** [comment]
This is done in #371
